# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subApp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmodel',
            name='person_ID',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='expiredAt',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='person',
            name='extNum',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminModel',
        ),
    ]
