# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subApp1', '0002_auto_20180526_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='catalogType_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogTypeFrom', to='subApp1.CatalogType'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='person_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personIDFrom', to='subApp1.Person'),
        ),
    ]
